Numpy is an open source python library thats widely used in science and engineering. The Numpy library contains multidimensional array datastructures, such as homogenous, N-Dimensional ndarray and a large library of function that operates effeciently on these data structures.


## How to import Numpy

After installing numpy , it may be imported into python code like:

In [1]:
import numpy as np

## Why use Numpy?

Python Lists are execellent, general-prurpose containers. They can be 'heterogeneous', meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.


### What is an "array"?

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages. In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called **ndarray**: it represents an **“N-dimensional array”**.

Most NumPy arrays have some restrictions. For instance:

1. All elements of the array must be of the same type of data.

2. Once created, the total size of the array can’t change.

3. The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

### Array Fundamentals:



In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

Elements of an array can be accessed in various ways. For instance, we can access an individual element of this array as we would access an element in the original list: using the integer index of the element within square brackets.

In [3]:
a[0]

np.int64(1)

In [4]:
# Arrays are mutable
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [5]:
# We can slice array just like list
a[:3]


array([10,  2,  3])

One major difference is that **slice indexing of a list** copies the elements into a new list, but slicing an array returns a **view**: an object that refers to the data in the original array. The original array can be mutated using the view.

In [6]:
b = a[:3]
b

array([10,  2,  3])

In [7]:
b[0] = 50
a

array([50,  2,  3,  4,  5,  6])

In [9]:
## Two and higher dimentional arrays:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In NumPy, a dimension of an array is sometimes referred to as an “axis”. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array a could represent three points, each lying within a four-dimensional space, but a has only two “axes”.

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3:

In [10]:
a[1,3]

np.int64(8)

### Array Attributes

This section covers *ndims*, *shape*, *size* and *dtype* attributes of the array.

The number of dimesions of an array is contained in the *ndim* attribute

In [11]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [12]:
a.shape

(3, 4)

In [14]:
len(a.shape) == a.ndim

True

The fixed, total number of elements in array is contained in the size attribute.



In [15]:
a.size

12

In [16]:
import math
a.size == math.prod(a.shape)

True

Arrays are typically **“homogeneous”**, meaning that they contain elements of only one “data type”. The data type is recorded in the **dtype** attribute.

In [17]:
a.dtype

dtype('int64')

### How to create a basic array

This section covers creation of array:

Besides creating an array from a sequence of elements , you can easily create an array filled with **0's**:

In [18]:
np.zeros(2)

array([0., 0.])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

Or even an empty array! The function **empty** creates an array whose initial content is random and depends on the state of the memory. The reason to use **empty** over **zeros** (or something similar) is speed - just make sure to fill every element afterwards!

In [23]:
# Create an empty array with 2 elements
np.empty(3)

array([3., 2., 1.])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [26]:
np.arange(2,9,2)

array([2, 4, 6, 8])

You can also use **np.linspace()** to create an array with values that are spaced linearly in a specified interval:

In [27]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.linspace(0,10,num=2)

array([ 0., 10.])

##### Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [29]:
X = np.ones(2, dtype=np.int64)
X

array([1, 1])