### Adding, removing and sorting elements

Soring an array is simple with **np.sort()**. You can specify the axis , kind and order when you call the function.

In [2]:
import numpy as np

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [4]:
# Sorting Array Elements in ascending order
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:

1. **argsort**, which is an indirect sort along a specified axis,

2. **lexsort**, which is an indirect stable sort on multiple keys,

3. **searchsorted**, which will find elements in a sorted array, and

4. **partition**, which is a partial sort.



In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with **np.concatenate()**.



In [6]:
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [9]:
np.concatenate((x,y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep.


### How do you know the shape and size of an array?


1. **ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

2. **ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

3. **ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [10]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

To find the number of dimensions of the array, run:



In [11]:
array_example.ndim

3

To find the total number of elements in the array, run:



In [12]:
array_example.size

24

And to find the shape of your array, run:



In [13]:
array_example.shape

(3, 2, 4)

### Can you Reshape an array?

**Yes!**

Using **arr.reshape()** will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.



In [15]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

You can use **reshape()** to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

In [16]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

With **np.reshape**, you can specify a few optional parameters:



In [17]:
np.reshape(a,shape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

1. **a** : Is the array to be reshaped.

2. **shape**: Is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

3. **order**: 
   
   **C** means to read/write the elements using C-like index order, 

   **F** means to read/write the elements using Fortran-like index order,
   
   **A** means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

### How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use **np.newaxis** and **np.expand_dims** to increase the dimensions of your existing array.

Using **np.newaxis** will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [18]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

You can use **np.newaxis** to add a new axis:



In [20]:
a2 = a[np.newaxis,:]
a2

array([[1, 2, 3, 4, 5, 6]])

You can explicitly convert a 1D array to either a row vector or a column vector using **np.newaxis**. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:



In [21]:
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

Or, for a column vector, you can insert an axis along the second dimension:



In [22]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with **np.expand_dims**.

In [23]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

You can use **np.expand_dims** to add an axis at index position 1 with:



In [24]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [25]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)